language: haskell
sudo: required

git:
  depth: 5

cabal: "2.4"

cache:
  directories:
    - "$HOME/.cabal/store"
    - "$HOME/.stack"
    - "$TRAVIS_BUILD_DIR/.stack-work"

matrix:
  include:

    # Cabal
    - ghc: 8.8.1
    - ghc: 8.6.5
    - ghc: 8.4.4
    - ghc: 8.2.2

    # Stack
    - ghc: 8.6.5
      env: STACK_YAML="$TRAVIS_BUILD_DIR/stack.yaml"

before_install:
  - sudo add-apt-repository ppa:hvr/ghc -y
  - sudo apt-get update -q
  - sudo apt-get install cabal-install-3.0 -y

install:
  - |
    if [ -z "$STACK_YAML" ]; then
      ghc --version
      cabal --version
      cabal new-update
      cabal new-build --enable-tests --enable-benchmarks
    else
      # install stack
      curl -sSL https://get.haskellstack.org/ | sh

      # build project with stack
      stack --version
      stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks
    fi

script:
  - |
    if [ -z "$STACK_YAML" ]; then
      cabal new-test --enable-tests
    else
      stack test --system-ghc
    fi

  - curl -sSL https://raw.github.com/ndmitchell/neil/master/misc/travis.sh | sh -s -- hlint .
